# Use this file to configure the Overcommit hooks you wish to use. This will
# extend the default configuration defined in:
# https://github.com/sds/overcommit/blob/master/config/default.yml
#
# At the topmost level of this YAML file is a key representing type of hook
# being run (e.g. pre-commit, commit-msg, etc.). Within each type you can
# customize each hook, such as whether to only run it on certain files (via
# `include`), whether to only display output if it fails (via `quiet`), etc.
#
# For a complete list of hooks, see:
# https://github.com/sds/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/sds/overcommit#configuration
#
# Uncomment the following lines to make the configuration take effect.

#PreCommit:
#  RuboCop:
#    enabled: true
#    on_warn: fail # Treat all warnings as failures
#
#  TrailingWhitespace:
#    enabled: true
#    exclude:
#      - '**/db/structure.sql' # Ignore trailing whitespace in generated files
#
#PostCheckout:
#  ALL: # Special hook name that customizes all hooks of this type
#    quiet: true # Change all post-checkout hooks to only display output on failure
#
#  IndexTags:
#    enabled: true # Generate a tags file with `ctags` each time HEAD changes
PreCommit:
  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop']

  SCSSLint:
    enabled: true
    required_executable: 'scss-lint'
    command: ['bundle', 'exec', 'scss-lint']
    include:
      - '**/*.scss'
    exclude:
      - 'vendor/**/*'
      - 'node_modules/**/*'

  ForbiddenPatterns:
    enabled: true
    exclude: []
    pattern: '\.env'
    message: 'Never commit .env files'

  TrailingWhitespace:
    enabled: true
    exclude:
      - '**/db/structure.sql'
  Brakeman:
    enabled: true
    required_executable: 'brakeman'
    command: ['bundle', 'exec', 'brakeman', '-q', '-w2']

  BundlerAudit:
    enabled: true
    required_executable: 'bundler-audit'
    command: ['bundle', 'exec', 'bundler-audit', 'check', '--update']
    args: []

CommitMsg:
  EmptyMessage:
    enabled: false
  TextWidth:
    enabled: true
    max_subject_width: 72
  MessageFormat:
    enabled: true
    format: '/^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?\s\|\s.+\s\|\s.+$/'
    error_message:
      'Your commit message must follow: <type>(<scope>) | <description> |
      <developers>'
  SpellCheck:
    enabled: false
  CapitalizedSubject:
    enabled: false

PrePush:
  RunTests:
    enabled: true
    required_executable: 'rails'
    command: ['bundle', 'exec', 'rails', 'test']
    args: []
  # PendingMigrations:
  #   enabled: true
  #   command: ['bundle', 'exec', 'rails', 'db:abort_if_pending_migrations']
  #   args: []
